### ISSUE TITLE
PlayerDisguise skin sometimes not appearing for the client

### ISSUE THREAD

**Issue by Arektor** [libraryaddict/LibsDisguises#151]
`this.usedSkin = (this.possibleSkins.size() <= 1 ? this.possibleSkins.get(0) : this.possibleSkins.get(new Random().nextInt(this.possibleSkins.size())));`

`PlayerDisguise playerDisguise = new PlayerDisguise(usedSkin);`
`playerDisguise.setDisguiseTarget(TargetType.SHOW_TO_EVERYONE_BUT_THESE_PLAYERS);`
`playerDisguise.setReplaceSounds(false);`
`PlayerWatcher pw = playerDisguise.getWatcher();`
`pw.setMainHand(new Random().nextInt(100)+1 >= 95 ? MainHand.LEFT : MainHand.RIGHT);`
`playerDisguise.setWatcher(pw);`

`DisguiseAPI.disguiseEntity(this.getBEntity(), playerDisguise);`

That is the part of code used for disguising my entity, where "usedSkin" is a WrappedGameProfile.
In common conditions, this works well. The disguise have the skin, everything's good.

But if this entity is not rendered on my screen (so, for example, is behind me), the disguise will just have the default skin.
The same goes for when you go far enough for the entity to disappear and you come back close enough for it to appear when you're not looking at it.

Tested on two different server, one running other plugins, one running only LibsDisguises and ProtocolLib.
Also tested with the /disguiseplayer command on a friend of mine: the disguise won't have any skin.
(I tried to update to the latest build of spigot, nothing changes.)
No errors in the logs.

Using Spigot 1.10.2 build 898
Using LibsDisguises Jenkins build 49
Using ProtocolLib build 297

**Easy way to reproduce:**
1. Spawn an entity, or ask a friend to come.
2. Disguise this entity / player into a player and specify the skin. (Haven't tested without)
   (/disguiseplayer YourFriend player RandomName setSkin PremiumUsername)
3. Go away from this entity / player, then go backward (so, without looking in the direction where you come from)
4. Once you are close enough, turn back: you will see a default skin.

**Comment by Arektor** [comment]
By playing around with the player disguise (thanks libraryaddict who helped me on some points), I found out that this bug does not happend if the fake player is still in the tab list.
A possible solution would be to send the packet for removing the fake player of the tab only once it is in the player's sight. (This is currently the only one I found yet)

**Comment by libraryaddict** [comment]
Should be fixed, reopen if still a bug

**Comment by Arektor** [comment]
Just tested with the latest build on jenkins (Build 81) and it has been half fixed.
Let me explain what happends now:

By doing the same process as described previously, when I turn around, the player disguises that are far away still have their skin.
However, those who are close to me when I turn back doesn't.

Still happening also when you look at your feets and walk toward the disguises, then look back at them.
That's kinda weird, and illogical ._.
